echo "Install essential packages"

apt-get install -y \
    acl \
    apt-transport-https \
    build-essential \
    ca-certificates \
    cron \
    curl \
    debian-archive-keyring \
    debian-keyring \
    fail2ban \
    g++ \
    gcc \
    gifsicle \
    git \
    gnupg \
    htop \
    iproute2 \
    jpegoptim \
    jq \
    libmagickwand-dev \
    libmcrypt4 \
    libonig-dev \
    libpcre3-dev \
    libpng-dev \
    libzip-dev \
    lsb-release \
    make \
    nano \
    ncdu \
    net-tools \
    optipng \
    pkg-config \
    pngquant \
    procps \
    python3 \
    python3-pip \
    sendmail \
    software-properties-common \
    sudo \
    supervisor \
    ufw \
    unattended-upgrades \
    unzip \
    uuid-runtime \
    vim \
    wget \
    whois \
    zip \
    zsh